# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: git@github.com:AM-OperatingSystem/hooks.git
    rev: ab66d648103e7aca200d5e715968a34576a166e2
    hooks:
    - id: cargo-check
    - id: cargo-clippy
    - id: cargo-test
