[workspace]

members = [
    "vidmod-core",
    "vidmod-node",
    "vidmod-tests",
    "vidmod-plugin",
    "vidmod-macros",
    "vidmod-plugins/vidmod-plugins-cvbs",
    "vidmod-plugins/vidmod-plugins-core",
    "vidmod-plugins/vidmod-plugins-dsp",
]
