[package]
name = "vidmod-tests"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
checksums = "0.9.1"
tracing-subscriber = "0.3.9"
vidmod-core = { version = "0.1.0", path = "../vidmod-core" }
