[package]
name = "vidmod-tests"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
data-encoding = "2.3.2"
sha2 = "0.10.2"
vidmod-core = { version = "0.1.0", path = "../vidmod-core" }
