[package]
name = "vidmod-node"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
all_asserts = "2.3.1"
anyhow = "1.0.55"
ndarray = "0.15.4"
vidmod-macros = { version = "0.1.0", path = "../vidmod-macros" }
